// src/components/ProductFeatures.tsx
import React from 'react';
import { motion } from 'framer-motion';

interface ProductCardProps {
  icon: string;
  title: string;
  features: string[];
  scenarios: string;
}

const ProductCard: React.FC<ProductCardProps> = ({ icon, title, features, scenarios }) => {
  return (
    <motion.div
      whileHover={{ y: -5, boxShadow: '0 10px 30px -10px rgba(59, 130, 246, 0.3)' }}
      className="bg-white rounded-xl border border-gray-100 p-6 shadow-md hover:border-blue-200 transition-all"
    >
      <div className="w-14 h-14 rounded-lg bg-blue-100 flex items-center justify-center text-blue-600 mb-5">
        <i className={`fas ${icon} text-2xl`}></i>
      </div>
      <h3 className="text-xl font-bold text-gray-900 mb-4">{title}</h3>
      <ul className="mb-5 space-y-2">
        {features.map((feature, index) => (
          <li key={index} className="flex items-start">
            <i className="fas fa-check text-green-500 mt-1 mr-2"></i>
            <span className="text-gray-600">{feature}</span>
          </li>
        ))}
      </ul>
      <div className="pt-4 border-t border-gray-100">
        <h4 className="font-semibold text-gray-800 mb-2">业务场景支撑:</h4>
        <p className="text-gray-600">{scenarios}</p>
      </div>
    </motion.div>
  );
};

const ProductFeatures: React.FC = () => {
  const products: ProductCardProps[] = [
    {
      icon: 'fa-comments',
      title: '智能问答',
      features: [
        '多轮对话：支持上下文理解，避免重复提问',
        '多语种：覆盖中、英、日等8种语言',
        '知识库联动：自动对接企业知识库，精准引用数据',
        '智能转人工：复杂问题一键转接人工，保留对话记录'
      ],
      scenarios: '客户服务（自动响应咨询）、内部培训（员工答疑）、售后支持（故障排查）'
    },
    {
      icon: 'fa-tasks',
      title: '智能协办',
      features: [
        '任务自动化：自动分配任务、发送提醒（如项目节点通知）',
        '流程优化：识别协作瓶颈，推荐最优流程',
        '文档协同：支持多人实时编辑，自动生成修订记录',
        '跨部门联动：打破数据壁垒，同步信息'
      ],
      scenarios: '项目管理（进度跟踪）、跨部门协作（需求同步）、行政事务（考勤/报销提醒）'
    },
    {
      icon: 'fa-chart-line',
      title: '智能报告',
      features: [
        '自动生成：接入业务数据，一键生成可视化报告（折线图/柱状图/饼图）',
        '自定义模板：支持企业自定义报告格式（如周报/月报）',
        '智能解读：用自然语言解读数据结论，降低理解门槛',
        '多端导出：支持PDF/Excel/PPT格式导出'
      ],
      scenarios: '数据分析（业务复盘）、管理层汇报（决策支持）、市场调研（趋势总结）'
    },
    {
      icon: 'fa-database',
      title: '智能问数',
      features: [
        '自然语言查询：用日常语言提问（如"本月电商销售额Top3品类"），无需SQL',
        '实时计算：对接实时数据，秒级返回查询结果',
        '数据钻取：支持多层级拆解数据（如"销售额→地区→门店"）',
        '异常预警：自动识别数据异常（如销量骤降），推送提醒'
      ],
      scenarios: '运营分析（实时监控）、财务核算（数据查询）、供应链管理（库存预警）'
    }
  ];

  return (
    <section id="product" className="py-20 bg-white">
      <div className="container mx-auto px-4">
        {/* Section Title */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.h2 
            className="text-3xl md:text-4xl font-bold mb-3 text-gray-900"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-blue-400">
              核心产品 | 四大AI能力，支撑全业务场景
            </span>
          </motion.h2>
          <motion.div 
            className="w-20 h-1 bg-blue-600 mx-auto mb-6"
            initial={{ width: 0 }}
            whileInView={{ width: 80 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            viewport={{ once: true }}
          ></motion.div>
          <motion.p 
            className="text-gray-600 text-lg"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            viewport={{ once: true }}
          >
            博智星智能体整合四大核心AI能力，为企业提供全方位的智能解决方案，提升业务效率与决策质量。
          </motion.p>
        </div>

        {/* Product Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
          {products.map((product, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              viewport={{ once: true }}
            >
              <ProductCard {...product} />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProductFeatures;

// src/components/ProductFeatures.vue
<template>
  <section id="product" class="py-20 bg-white overflow-hidden">
    <div class="container mx-auto px-4">
      <!-- Section Header -->
      <div class="text-center mb-16 animate-fade-in-up">
        <h2 class="text-3xl md:text-4xl font-bold mb-4 text-gray-900 relative inline-block">
          <span class="relative z-10">核心产品</span>
          <span class="absolute -bottom-2 left-0 w-full h-3 bg-blue-100 opacity-70 z-0 transform -rotate-1"></span>
        </h2>
        <p class="text-lg text-gray-600 max-w-3xl mx-auto mt-6">
          博智星智能体提供四大核心产品能力，助力企业实现智能化升级，提升运营效率和决策质量
        </p>
      </div>

      <!-- Product Features Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <!-- 智能问答 -->
        <div class="bg-white rounded-xl shadow-lg p-6 border border-gray-100 transform transition-all duration-500 hover:scale-105 hover:shadow-xl animate-fade-in-up animation-delay-200 group">
          <div class="w-14 h-14 rounded-full bg-blue-100 flex items-center justify-center mb-6 transform transition-all duration-300 group-hover:bg-blue-600 group-hover:scale-110">
            <i class="fas fa-robot text-blue-600 text-2xl transform transition-all duration-300 group-hover:text-white"></i>
          </div>
          <h3 class="text-xl font-semibold mb-3 text-gray-900 transition-colors duration-300 group-hover:text-blue-600">智能问答</h3>
          <p class="text-gray-600 mb-4 transition-all duration-300">
            基于大语言模型的智能问答系统，快速响应客户咨询，提供精准解答，支持多轮对话和复杂问题处理
          </p>
          <a href="#" class="inline-flex items-center text-blue-600 font-medium hover:text-blue-700 transition-all duration-300 group-hover:translate-x-1">
            了解更多
            <i class="fas fa-arrow-right ml-2 text-sm transform transition-transform duration-300 group-hover:translate-x-1"></i>
          </a>
        </div>

        <!-- 智能协办 -->
        <div class="bg-white rounded-xl shadow-lg p-6 border border-gray-100 transform transition-all duration-500 hover:scale-105 hover:shadow-xl animate-fade-in-up animation-delay-300 group">
          <div class="w-14 h-14 rounded-full bg-green-100 flex items-center justify-center mb-6 transform transition-all duration-300 group-hover:bg-green-600 group-hover:scale-110">
            <i class="fas fa-tasks text-green-600 text-2xl transform transition-all duration-300 group-hover:text-white"></i>
          </div>
          <h3 class="text-xl font-semibold mb-3 text-gray-900 transition-colors duration-300 group-hover:text-green-600">智能协办</h3>
          <p class="text-gray-600 mb-4 transition-all duration-300">
            AI驱动的任务协作助手，自动化处理日常工作，智能调度资源，提升团队协作效率和执行力
          </p>
          <a href="#" class="inline-flex items-center text-blue-600 font-medium hover:text-blue-700 transition-all duration-300 group-hover:translate-x-1">
            了解更多
            <i class="fas fa-arrow-right ml-2 text-sm transform transition-transform duration-300 group-hover:translate-x-1"></i>
          </a>
        </div>

        <!-- 智能报告 -->
        <div class="bg-white rounded-xl shadow-lg p-6 border border-gray-100 transform transition-all duration-500 hover:scale-105 hover:shadow-xl animate-fade-in-up animation-delay-400 group">
          <div class="w-14 h-14 rounded-full bg-purple-100 flex items-center justify-center mb-6 transform transition-all duration-300 group-hover:bg-purple-600 group-hover:scale-110">
            <i class="fas fa-chart-line text-purple-600 text-2xl transform transition-all duration-300 group-hover:text-white"></i>
          </div>
          <h3 class="text-xl font-semibold mb-3 text-gray-900 transition-colors duration-300 group-hover:text-purple-600">智能报告</h3>
          <p class="text-gray-600 mb-4 transition-all duration-300">
            自动数据收集、分析和报告生成，支持多维度数据可视化，助力企业快速洞察业务趋势和决策优化
          </p>
          <a href="#" class="inline-flex items-center text-blue-600 font-medium hover:text-blue-700 transition-all duration-300 group-hover:translate-x-1">
            了解更多
            <i class="fas fa-arrow-right ml-2 text-sm transform transition-transform duration-300 group-hover:translate-x-1"></i>
          </a>
        </div>

        <!-- 智能问数 -->
        <div class="bg-white rounded-xl shadow-lg p-6 border border-gray-100 transform transition-all duration-500 hover:scale-105 hover:shadow-xl animate-fade-in-up animation-delay-500 group">
          <div class="w-14 h-14 rounded-full bg-amber-100 flex items-center justify-center mb-6 transform transition-all duration-300 group-hover:bg-amber-600 group-hover:scale-110">
            <i class="fas fa-database text-amber-600 text-2xl transform transition-all duration-300 group-hover:text-white"></i>
          </div>
          <h3 class="text-xl font-semibold mb-3 text-gray-900 transition-colors duration-300 group-hover:text-amber-600">智能问数</h3>
          <p class="text-gray-600 mb-4 transition-all duration-300">
            自然语言查询数据分析工具，无需编写SQL，通过对话式交互快速获取数据洞察，降低数据分析门槛
          </p>
          <a href="#" class="inline-flex items-center text-blue-600 font-medium hover:text-blue-700 transition-all duration-300 group-hover:translate-x-1">
            了解更多
            <i class="fas fa-arrow-right ml-2 text-sm transform transition-transform duration-300 group-hover:translate-x-1"></i>
          </a>
        </div>
      </div>

      <!-- Feature Highlights -->
      <div class="mt-20">
        <div class="flex flex-col lg:flex-row items-center">
          <div class="lg:w-1/2 mb-10 lg:mb-0 lg:pr-12">
            <h3 class="text-2xl font-bold mb-6 text-gray-900">企业级AI解决方案，一站式满足多元需求</h3>
            <ul class="space-y-4">
              <li class="flex items-start">
                <div class="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center mt-1 mr-3 flex-shrink-0">
                  <i class="fas fa-check text-blue-600 text-sm"></i>
                </div>
                <div>
                  <span class="font-medium text-gray-900">多模型支持：</span>
                  <span class="text-gray-600">集成主流大语言模型，灵活切换，满足不同场景需求</span>
                </div>
              </li>
              <li class="flex items-start">
                <div class="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center mt-1 mr-3 flex-shrink-0">
                  <i class="fas fa-check text-blue-600 text-sm"></i>
                </div>
                <div>
                  <span class="font-medium text-gray-900">私有化部署：</span>
                  <span class="text-gray-600">支持企业内部私有化部署，保障数据安全和合规性</span>
                </div>
              </li>
              <li class="flex items-start">
                <div class="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center mt-1 mr-3 flex-shrink-0">
                  <i class="fas fa-check text-blue-600 text-sm"></i>
                </div>
                <div>
                  <span class="font-medium text-gray-900">行业适配：</span>
                  <span class="text-gray-600">针对不同行业定制化训练，提供更专业的智能服务</span>
                </div>
              </li>
              <li class="flex items-start">
                <div class="w-6 h-6 rounded-full bg-blue-100 flex items-center justify-center mt-1 mr-3 flex-shrink-0">
                  <i class="fas fa-check text-blue-600 text-sm"></i>
                </div>
                <div>
                  <span class="font-medium text-gray-900">持续学习：</span>
                  <span class="text-gray-600">系统自动学习用户反馈，不断优化服务质量和准确性</span>
                </div>
              </li>
            </ul>
          </div>
          <div class="lg:w-1/2">
            <div class="bg-gradient-to-tr from-blue-50 to-indigo-50 rounded-2xl p-8 shadow-xl">
              <div class="flex items-center mb-6">
                <div class="w-12 h-12 rounded-full bg-blue-600 flex items-center justify-center mr-4">
                  <i class="fas fa-shield-alt text-white text-xl"></i>
                </div>
                <div>
                  <h4 class="text-xl font-semibold text-gray-900">安全与合规</h4>
                  <p class="text-gray-600">企业级数据安全保障</p>
                </div>
              </div>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div class="bg-white p-4 rounded-lg shadow">
                  <div class="flex items-center mb-2">
                    <i class="fas fa-lock text-blue-600 mr-2"></i>
                    <h5 class="font-medium text-gray-900">数据加密</h5>
                  </div>
                  <p class="text-sm text-gray-600">全链路数据加密，保障数据传输和存储安全</p>
                </div>
                <div class="bg-white p-4 rounded-lg shadow">
                  <div class="flex items-center mb-2">
                    <i class="fas fa-user-shield text-blue-600 mr-2"></i>
                    <h5 class="font-medium text-gray-900">权限管理</h5>
                  </div>
                  <p class="text-sm text-gray-600">精细化权限控制，确保数据访问安全合规</p>
                </div>
                <div class="bg-white p-4 rounded-lg shadow">
                  <div class="flex items-center mb-2">
                    <i class="fas fa-history text-blue-600 mr-2"></i>
                    <h5 class="font-medium text-gray-900">审计追踪</h5>
                  </div>
                  <p class="text-sm text-gray-600">完整操作日志记录，支持审计和追溯</p>
                </div>
                <div class="bg-white p-4 rounded-lg shadow">
                  <div class="flex items-center mb-2">
                    <i class="fas fa-certificate text-blue-600 mr-2"></i>
                    <h5 class="font-medium text-gray-900">合规认证</h5>
                  </div>
                  <p class="text-sm text-gray-600">符合多项行业标准和数据保护法规要求</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// ProductFeatures组件逻辑
</script>

<style scoped>
/* Animation classes */
.animate-fade-in-up {
  animation: fadeInUp 0.8s ease forwards;
  opacity: 0;
}

/* Animation delays */
.animation-delay-200 {
  animation-delay: 200ms;
}

.animation-delay-300 {
  animation-delay: 300ms;
}

.animation-delay-400 {
  animation-delay: 400ms;
}

.animation-delay-500 {
  animation-delay: 500ms;
}

/* Keyframes */
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Group hover effects */
.group:hover h3 {
  transform: translateX(5px);
}

/* Link hover effect */
a:hover {
  text-decoration: underline;
}
</style>
